### ISSUE TITLE
Test fails with 1 and 1 as parameters

### ISSUE THREAD

**Issue by ericsiber** [Mohamed-Mehdi/FizzBuzz#1]
See resulting output : 

> tests with n1= 1 and n2= 1
> .F...
> 
> Failures:
> 
>   1) FizzBuzz Test should have 1 as first element
>    Message:
>      Expected 'FizzBuzz' to be 1.
>    Stacktrace:
>      Error: Expected 'FizzBuzz' to be 1.
>     at null.<anonymous> (/Users/esiber/Downloads/FizzBuzz-master/spec/FizzBuzz.spec.js:21:37)
> 
> Finished in 0.01 seconds
> 5 tests, 101 assertions, 1 failure, 0 skipped

**Comment by mm-saad** [comment]
J’ai pas fait attention pour ce cas !

EN fait, j’ai modifié les tests, au lieu du ce test statique, j’ai créé un autre test qui parcours tous les éléments qui ne sont ni divisible par le premier numéro ni par le deuxième. Avec ce test-là, on a toujours 100 assertions, c’est-à-dire on vérifie tous les éléments de 1 à 100 pour n’importe quelle pair de numéros.
J’ai aussi traité le cas où n1 ou n2 <1 (on fait les tests avec (3,5)).
L’adresse du repo git est :  https://github.com/Mohamed-Mehdi/FizzBuzz

Mercii

Mehdi.

De : Eric Siber [mailto:notifications@github.com]
Envoyé : lundi 15 août 2016 19:32
À : Mohamed-Mehdi/FizzBuzz FizzBuzz@noreply.github.com
Objet : [Mohamed-Mehdi/FizzBuzz] Test fails with 1 and 1 as parameters (#1)

See resulting output :

tests with n1= 1 and n2= 1
.F...

Failures:

1) FizzBuzz Test should have 1 as first element
Message:
Expected 'FizzBuzz' to be 1.
Stacktrace:
Error: Expected 'FizzBuzz' to be 1.
at null. (/Users/esiber/Downloads/FizzBuzz-master/spec/FizzBuzz.spec.js:21:37)

Finished in 0.01 seconds
5 tests, 101 assertions, 1 failure, 0 skipped
