### ISSUE TITLE
Bad results when one parameter is 1

### ISSUE THREAD

**Issue by ericsiber** [Mohamed-Mehdi/FizzBuzz#2]
Enter first number : 1
Enter second number : 5

> [ 'FizzBuzz',
>   'FizzBuzz',
>   'FizzBuzz',
>   'FizzBuzz',
>   'FizzBuzz',
>   'FizzBuzz',
>   'FizzBuzz',
>   'FizzBuzz',
>   'FizzBuzz',
>   'FizzBuzz',

Enter first number : 5
Enter second number : 1

> [ 1,
>   2,
>   3,
>   4,
>   'FizzBuzz',
>   6,
>   7,
>   8,
>   9,
>   'FizzBuzz',

**Comment by mm-saad** [comment]
Salut Eric,

J’ai résolu le prob, c’était dans le fichier server.js dans l’opérateur ternaire, j’ai mis n1 au lieu de n2.

Merci.

De : Eric Siber [mailto:notifications@github.com]
Envoyé : mardi 16 août 2016 13:46
À : Mohamed-Mehdi/FizzBuzz FizzBuzz@noreply.github.com
Objet : [Mohamed-Mehdi/FizzBuzz] Bad results when one parameter is 1 (#2)

Enter first number : 1
Enter second number : 5

[ 'FizzBuzz',
'FizzBuzz',
'FizzBuzz',
'FizzBuzz',
'FizzBuzz',
'FizzBuzz',
'FizzBuzz',
'FizzBuzz',
'FizzBuzz',
'FizzBuzz',

Enter first number : 5
Enter second number : 1

[ 1,
2,
3,
4,
'FizzBuzz',
6,
7,
8,
9,
'FizzBuzz',
